services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=relay_dev
      - POSTGRES_USER=relay
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Set Password}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: